spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbs?createDatabaseIfNotExist=true
    username: root
    password: mngtvarshney
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
